name: '🚀 [Azure] Build and deploy'

# Secrets used in this GitHub workflow:
# - GH_TOKEN_READ_PACKAGES
# Vars used in this GitHub workflow:
# - BUILDER_CLIENT_ID
# - GH_USERNAME_READ_PACKAGES
# - RESOURCE_GROUP_NAME
# - SUBSCRIPTION_ID
# - TENANT_ID

on:
  push:
    branches: ['main']
  workflow_dispatch: {}

concurrency:
  group: 'azure'
  cancel-in-progress: true

env:
  DEPLOYMENT_FAMILY_NAME: ${{ vars.DEPLOYMENT_FAMILY_NAME }}
  IMAGE_NAME_WITHOUT_OWNER: ${{ github.event.repository.name }}
  NODE_VERSION: current
  REGISTRY: ghcr.io

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Bicep templates
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: bicep
          path: ./bicep
          retention-days: 1

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Clean install
        run: npm clean-install

      - name: Build
        run: npm run build

      - name: Pack bot
        run: npm pack
        working-directory: ./packages/bot

      - name: Upload bot tarball
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: bot-tarball
          path: ./packages/bot/*.tgz
          retention-days: 1

      - name: Pack token service
        run: npm pack
        working-directory: ./packages/token-service

      - name: Upload token service tarball
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: token-service-tarball
          path: ./packages/token-service/*.tgz
          retention-days: 1

  convert-bot-deployment:
    name: Convert bot tarball to ZIP deployment
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Download tarball
        uses: actions/download-artifact@v4
        with:
          name: bot-tarball

      - name: Extract tarball
        run: |
          mkdir ./deploy
          cd ./deploy
          tar xvf ../*.tgz --strip-components=1

      - name: List directory
        run: ls -laR
        working-directory: ./deploy

      - name: Compress as ZIP
        run: zip -r ../bot.zip .
        working-directory: ./deploy

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: bot-zip
          path: ./bot.zip
          retention-days: 1

  publish-containers:
    name: Publish containers
    needs: build
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [token-service]

    steps:
      - name: Download tarball
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.name }}-tarball

      - run: mkdir ./deploy

      - name: Extract tarball
        run: tar xvf ./*.tgz --strip-components=1

      - name: List directory
        run: ls -la

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_WITHOUT_OWNER }}-${{ matrix.name }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=sha,format=long

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./ # Required
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-bicep:
    environment: azure
    name: Deploy Bicep
    needs: publish-containers
    outputs:
      bot-app-name: ${{ steps.deploy-to-azure.outputs.botAppName }}
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Download Bicep templates
        uses: actions/download-artifact@v4
        with:
          name: bicep

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.BUILDER_CLIENT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}
          tenant-id: ${{ vars.TENANT_ID }}

      - id: prepare
        name: Prepare parameters
        run: |
          echo PARAMETERS=$((cat <<EOF
            {
              "builderIdentityName": "${{ env.DEPLOYMENT_FAMILY_NAME }}-builder-identity",
              "deploymentFamilyName": "${{ env.DEPLOYMENT_FAMILY_NAME }}",
              "registryPassword": "${{ secrets.GH_TOKEN_READ_PACKAGES }}",
              "registryServer": "${{ env.REGISTRY }}",
              "registryUsername": "${{ vars.GH_USERNAME_READ_PACKAGES }}",
              "tokenServiceImageName": "${{ github.repository_owner }}/${{ env.IMAGE_NAME_WITHOUT_OWNER }}-token-service:sha-${{ github.sha }}"
            }
          EOF
          ) | jq -r '. | to_entries | map(.key + "=" + (.value | tostring)) | join(" ")') | tee --append $GITHUB_OUTPUT

      - id: deploy-to-azure
        name: Deploy to Azure
        uses: azure/arm-deploy@v2
        with:
          failOnStdErr: false
          parameters: ${{ steps.prepare.outputs.PARAMETERS }}
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          template: ./main.bicep

  deploy-to-web-apps:
    environment: azure
    name: Deploy to Web Apps
    needs:
      - convert-bot-deployment
      - deploy-bicep
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Download tarball
        uses: actions/download-artifact@v4
        with:
          name: bot-zip

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.BUILDER_CLIENT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}
          tenant-id: ${{ vars.TENANT_ID }}

      - uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ needs.deploy-bicep.outputs.bot-app-name }}
          package: ./bot.zip

  cleanup:
    name: Cleanup
    continue-on-error: true
    needs: publish-containers
    permissions:
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [token-service]

    steps:
      - name: Delete obsoleted images
        continue-on-error: true
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.IMAGE_NAME_WITHOUT_OWNER }}-${{ matrix.name }}
          package-type: container
          min-versions-to-keep: 5
