name: '🚀 [Azure] Build and deploy'

# Secrets used in this GitHub workflow:
# - GH_TOKEN_READ_PACKAGES
# Vars used in this GitHub workflow:
# - BUILDER_CLIENT_ID
# - GH_USERNAME_READ_PACKAGES
# - RESOURCE_GROUP_NAME
# - SUBSCRIPTION_ID
# - TENANT_ID

on:
  push:
    branches: ['main']
  schedule:
    - cron: '0 4 * * 1'
  workflow_dispatch: {}

concurrency:
  group: 'azure'
  cancel-in-progress: true

env:
  DEPLOYMENT_FAMILY_NAME: ${{ vars.DEPLOYMENT_FAMILY_NAME }}
  IMAGE_NAME_WITHOUT_OWNER: ${{ github.event.repository.name }}
  NODE_VERSION: 22.4
  REGISTRY: ghcr.io

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Bicep templates
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: bicep
          path: ./bicep
          retention-days: 1

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ env.NODE_VERSION }}

      - name: Clean install
        run: npm clean-install

      - name: Build
        run: npm run build

      - name: Pack echo-bot-app
        run: npm pack
        working-directory: ./packages/echo-bot-app

      - name: Upload echo-bot-app tarball
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: echo-bot-app-tarball
          path: ./packages/echo-bot-app/*.tgz
          retention-days: 1

      - name: Pack mock-bot-app
        run: npm pack
        working-directory: ./packages/mock-bot-app

      - name: Upload mock-bot-app tarball
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: mock-bot-app-tarball
          path: ./packages/mock-bot-app/*.tgz
          retention-days: 1

      - name: Pack GitHub Pages
        run: npm pack
        working-directory: ./packages/pages

      - name: Upload GitHub Pages tarball
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: pages-tarball
          path: ./packages/pages/*.tgz
          retention-days: 1

      - name: Pack token-app
        run: npm pack
        working-directory: ./packages/token-app

      - name: Upload token-app tarball
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: token-app-tarball
          path: ./packages/token-app/*.tgz
          retention-days: 1

  convert-bot-app-artifact:
    name: Convert ${{ matrix.name }} tarball to ZIP deployment
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        name: [echo-bot-app, mock-bot-app]

    steps:
      - name: Download tarball
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.name }}-tarball

      - name: Extract tarball
        run: |
          mkdir ./${{ matrix.name }}
          cd ./${{ matrix.name }}
          tar xvf ../*.tgz --strip-components=1

      - name: List directory
        run: ls -laR
        working-directory: ./${{ matrix.name }}

      - name: Compress as ZIP
        run: zip -r ../${{ matrix.name }}.zip .
        working-directory: ./${{ matrix.name }}

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: ${{ matrix.name }}-zip
          path: ./${{ matrix.name }}.zip
          retention-days: 1

  publish-containers:
    name: Publish containers
    needs: build
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [token-app]

    steps:
      - name: Download tarball
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.name }}-tarball

      - name: Extract tarball
        run: |
          tar xvf ./*.tgz --strip-components=1
          rm ./*.tgz

      - name: List directory
        run: ls -la

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_WITHOUT_OWNER }}-${{ matrix.name }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=sha,format=long

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: . # Required
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-bicep:
    environment:
      name: azure
      url: ${{ steps.arm-deploy.outputs.mockBotAppURL }}health.txt
    name: Deploy Bicep
    needs: publish-containers
    outputs:
      echo-bot-app-name: ${{ steps.arm-deploy.outputs.echoBotAppName }}
      echo-bot-app-url: ${{ steps.arm-deploy.outputs.echoBotAppURL }}
      mock-bot-app-name: ${{ steps.arm-deploy.outputs.mockBotAppName }}
      mock-bot-app-url: ${{ steps.arm-deploy.outputs.mockBotAppURL }}
      token-app-url: ${{ steps.arm-deploy.outputs.tokenAppURL }}
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Download Bicep templates
        uses: actions/download-artifact@v4
        with:
          name: bicep

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.BUILDER_CLIENT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}
          tenant-id: ${{ vars.TENANT_ID }}

      - id: prepare
        name: Prepare parameters
        run: |
          echo PARAMETERS=$((cat <<EOF
            {
              "builderIdentityName": "${{ env.DEPLOYMENT_FAMILY_NAME }}-builder-identity",
              "deploymentFamilyName": "${{ env.DEPLOYMENT_FAMILY_NAME }}",
              "registryPassword": "${{ secrets.GH_TOKEN_READ_PACKAGES }}",
              "registryServer": "${{ env.REGISTRY }}",
              "registryUsername": "${{ vars.GH_USERNAME_READ_PACKAGES }}",
              "tokenAppImageName": "${{ github.repository_owner }}/${{ env.IMAGE_NAME_WITHOUT_OWNER }}-token-app:sha-${{ github.sha }}"
            }
          EOF
          ) | jq -r '. | to_entries | map(.key + "=" + (.value | tostring)) | join(" ")') | tee --append $GITHUB_OUTPUT

      - id: arm-deploy
        name: Deploy to Azure
        uses: azure/arm-deploy@v2
        with:
          failOnStdErr: false
          parameters: ${{ steps.prepare.outputs.PARAMETERS }}
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          template: ./main.bicep

  publish-echo-bot-app:
    environment:
      name: azure
      url: ${{ steps.webapps-deploy.outputs.webapp-url }}
    name: Publish echo-bot-app to Web Apps
    needs:
      - convert-bot-app-artifact
      - deploy-bicep
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Download tarball
        uses: actions/download-artifact@v4
        with:
          name: echo-bot-app-zip

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.BUILDER_CLIENT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}
          tenant-id: ${{ vars.TENANT_ID }}

      - id: webapps-deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ needs.deploy-bicep.outputs.echo-bot-app-name }}
          package: ./echo-bot-app.zip

  publish-mock-bot-app:
    environment:
      name: azure
      url: ${{ steps.webapps-deploy.outputs.webapp-url }}
    name: Publish mock-bot-app to Web Apps
    needs:
      - convert-bot-app-artifact
      - deploy-bicep
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Download tarball
        uses: actions/download-artifact@v4
        with:
          name: mock-bot-app-zip

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.BUILDER_CLIENT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}
          tenant-id: ${{ vars.TENANT_ID }}

      - id: webapps-deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ needs.deploy-bicep.outputs.mock-bot-app-name }}
          package: ./mock-bot-app.zip

  build-pages:
    name: Build GitHub Pages
    needs: deploy-bicep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Clean install
        run: npm clean-install

      - env:
          ECHO_BOT_APP_URL: ${{ needs.deploy-bicep.outputs.echo-bot-app-url }}
          MOCK_BOT_APP_URL: ${{ needs.deploy-bicep.outputs.mock-bot-app-url }}
          TOKEN_APP_URL: ${{ needs.deploy-bicep.outputs.token-app-url }}
        name: Build
        run: npm run build

      - name: List directory
        run: ls -laR
        working-directory: ./packages/pages/public

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./packages/pages/public/

  publish-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Publish to GitHub Pages
    needs: build-pages
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@main

  cleanup:
    name: Cleanup
    continue-on-error: true
    needs: publish-containers
    permissions:
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [token-app]

    steps:
      - name: Delete obsoleted images
        continue-on-error: true
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.IMAGE_NAME_WITHOUT_OWNER }}-${{ matrix.name }}
          package-type: container
          min-versions-to-keep: 5
